const btn = document.querySelector('.js-button');
const nav = document.querySelector('.js-nav')

btn.addEventListener('click', () => {
  nav.classList.toggle('active');
})

const container = document.querySelector('.js-card-container');

const projects = [
  {
    name: 'YouTube Clone',
    description: 'A landing page clone of YouTube.com',
    tags: 'HTML CSS',
    link: 'youtube.html',
    img: 'images/youtube-clone.PNG'
  },
  {
    name: 'Tic Tac Toe',
    description: 'A Tic Tac Toe game using the DOM',
    tags: 'HTML CSS JS',
    link: 'projects/tic-tac-toe-project/tic-tac-toe.html',
    img: 'images/tic-tac-toe.PNG'
  },
  {
    name: 'Menu',
    description: 'A Menu with HTML generated by JavaScript',
    tags: 'HTML CSS JS',
    link: 'projects/Menu Project/menu.html',
    img: 'images/menu.PNG'
  },
  {
    name: 'Color Flipper',
    description: 'A random background color generator',
    tags: 'HTML CSS JS',
    link: 'projects/Color Picker/picker.html',
    img: 'images/color-flipper.PNG'
  },
  {
    name: 'Rock Paper Scissors',
    description: 'A RPS game with autoplay feature',
    tags: 'HTML CSS JS',
    link: 'projects/rock-paper-scissors/rock-paper-scissors.html',
    img: 'images/rps.PNG'
  }
];

window.addEventListener('DOMContentLoaded', () => {
  displayCards(projects);
});

const displayCards = (projects) => {
  let cards = projects.map((item) => {
    return `
    <div class="card">
      <a href="${item.link}"><img src="${item.img}" alt="${item.name}"></a>
      <a href="${item.link}"><h3>${item.name}</h3></a>
      <p>${item.description}</p>
      <p class="tags">${item.tags}</p>
    </div>
    `
  });
  cards = cards.join("");
  container.innerHTML = cards;
}